### ISSUE TITLE
dump1090-mutability

### ISSUE THREAD

**Issue by marknfischer** [wiedehopf/combine1090#1]
This was working perfectly a couple days ago via dump1090-mutability, but now it won't allow install.  Any chance you can?  This code is so useful, but all of the code I'm maintaining is based off of a fork of dump1090-mutability.

**Comment by wiedehopf** [comment]
https://github.com/wiedehopf/combine1090#install-data-redirection-only

The combine1090-dump service was never working with dump1090-mutability.
So redirect only should be sufficient for you as ... without dump1090-fa you weren't using the rest of the install anyhow.
