### ISSUE TITLE
Running combine1090 user

### ISSUE THREAD

**Issue by marknfischer** [wiedehopf/combine1090#2]
Just installed fresh install, Readsb and Combine1090.  Combine1090 tried to run under user dump1090 which doesn't exist.  Switching to run under readsd user worked on my install, but would obviously break a dump1090 install w/o readsb.

**Comment by wiedehopf** [comment]
https://github.com/wiedehopf/combine1090/commit/fac2a8585a792924237ca770ec8e98010db52464
