### ISSUE TITLE
less data than "source"

### ISSUE THREAD

**Issue by messschuh** [wiedehopf/combine1090#5]
i installed readsb at two sbc`s. first one receives data via rtl-sdr , second one has no receiver but combine1090 are installed. at config i add the address of first Receiver and i get data of it, but when sbc 1 get 10 aircrafts, the second one(where combine1090 runs) gets 8 only.  where is the problem?

**Comment by wiedehopf** [comment]
Have you configured the location for combine1090?

Apart from that ... maybe you turned on P and didn't realize ....
Maybe they were just timing out ....

The software works, your report without further detail (screenshots count) isn't useful.
Closing.
