### ISSUE TITLE
Deprecated Message

### ISSUE THREAD

**Issue by atw527** [wiedehopf/combine1090#6]
This message has been showing up for a few months when viewing /combine1090/:

`This version of SkyAware will soon be deprecated. Visit URL: [local IP Address]/skyaware for the most up-to-date SkyAware interface.`

![image](https://user-images.githubusercontent.com/5099778/134556125-05baa4cb-2250-4166-888d-b17b97b93afc.png)

**Comment by wiedehopf** [comment]
So you report this without updating combine1090, update first, then report.

**Comment by atw527** [comment]
I did update.  Do I need to purge or uninstall it first?

**Comment by atw527** [comment]
Found another thread with a similar issue and found that restarting all the piaware-related services refreshed the map.  Maybe consider restarting those services in the install script.
