### ISSUE TITLE
How to: Actual range outline in combine1090

### ISSUE THREAD

**Issue by madjuju** [wiedehopf/combine1090#8]
Hello
Thank you for your excellent work and I use all the features you offer.

However, what is missing is the possibility to visualise "actual range ouline" on the combined view.

Would it be possible to add it?

Thanks in advance

Julien
![Sans titre](https://user-images.githubusercontent.com/5285199/187164568-d23ee641-e321-41eb-a77b-a2d8f9ddc516.jpg)

**Comment by wiedehopf** [comment]
Specify lat / lon in /etc/default/combine1090 in the options that are passed to readsb.
Like this:

```
DECODER_OPTIONS="--max-range 360 --lat 40.2 --lon 10.5"
```

**Comment by madjuju** [comment]
That have no effect.
Look my screen : 
On the left : http://192.168.1.39/combine1090/
On the right : http://192.168.1.39/tar1090/?
![2](https://user-images.githubusercontent.com/5285199/187169453-426128a5-56ea-4193-a2dd-8f62bb7311d0.jpg)

**Comment by wiedehopf** [comment]
Well you need to restart combine1090-dump.
Just do a reboot.

**Comment by madjuju** [comment]
already done before my last post

**Comment by wiedehopf** [comment]
Rerun the combine1090 install maybe you have an old version.
Or you have the configuration done wrong, post the entire file.

**Comment by madjuju** [comment]
My bad

duplicates "DECODER_OPTIONS=" in my /etc/default/combine1090 

Thanks you for your help

**Comment by wiedehopf** [comment]
Make sure each of your receivers is feeding adsbexchange if you like their page: https://globe.adsbexchange.com/
(don't feed combined data though)

**Comment by lx2r** [comment]
Hello,

Thank you @wiedehopf for all your great work with ADS-B! Your projects seem to cover almost every eventuality

I think this thread partially helps me in what I'm trying to achieve, but I wanted to check if I'm headed in the right direction, it's a similar issue as described above

At the moment I have a setup of a directional antenna connected to a receiver, running dump1090-fa. That receiver outputs Beast on 30005 which is read by Piaware, ADSBExchange-feed, fr24feed, PFClient, RBFeeder

Dump1090-fa receives MLAT feedback from Piaware and ADSBExchange-feed on port 30104 by the looks of things

Tar1090 runs two instances, one from the JSON written by dump1090-fa, which does not display an outline; and one from ADSBExchange-feed which is writing the outline.json file

Now if I want to go to a one-pi, two-receiver setup, with the directional antenna as above, and an omni, could you validate if the following would work without creating any conflicts:

- I run a second instance called dump1090-fa-2 on the second receiver, let's say Beast output on 39005 for instance
- That instance can feed FlightAware and ADSBExchange using a different sharing key in both cases (the antennas are only a matter of metres apart, but this seems safest?)
- I am presuming here that MLAT feedback would also come from FlightAware and ADSBExchange


This bit is where I get lost:
- Combine1090 will then run another net-only decoder instance on top of that, taking input from dump1090-fa and dump1090-fa-2 and output this in Beast (not sure what I would use this for, the data from both receivers would be shared independently, and combined data from what I understand, is not good for sharing) 
- Combine1090 would also write a JSON for Tar1090 to read, including an outline.json (this is the bit I'm looking for) and my MLAT results from both setups

Kind Regards
Royce

**Comment by wiedehopf** [comment]
It's not super simple to set up a 2nd feed client for FA / adsbexchange.

Honestly i doubt you'll get much extra with the directional antenna.

Just install combine1090 now and see what it does .... where the data comes from won't matter.

**Comment by toglo** [comment]
Hi! I cannot get the outline in combine1090 to work.

If I understood the above suggestions right, I need to add DECODER_OPTIONS to /etc/default/combine1090 and restart the pi.
Thats what I did - but I do not see any outline. I also did a second installation of combine1090 which didn't help.

My /etc/default/combine1090 contains this as its last line:
DECODER_OPTIONS="--max-range 360 --lat 48.7 --lon 9.1"

Combine1090 itself is working fine showing the planes of two local pi's running tar1090.

Any hints?
Thanks a lot!
Tobias

**Comment by wiedehopf** [comment]
i don't know what the issue is.
just tested, works fine for me.

can you share the output for 
```
pgrep -fa combine1090/bin
```

If it has lat and lon, should work fine.

**Comment by toglo** [comment]
I just double checked my /etc/default/combine1090.
That file is much longer as I initially thought! (Still getting used to nano...) There where indeed two lines of DECODER_OPTIONS in mine...

I fixed that and now it works! :-)

Thanks a lot!

**Comment by wiedehopf** [comment]
Some people might be interested in this:
<https://adsb.im/stage2>
